### PR TITLE
conversion from paper- to simple- in progress

### PR DESCRIPTION
**Pull request by nikkimk**

### CODE REVIEW

**Comment by btopro** [comment]
@ChristianMurphy whenever you get a chance could you look at the build failure? It's bizzare lol. Claiming that a relative reference is actually remote. Ever seen anything like that?

**Comment by ChristianMurphy** [comment]
I'm not as familiar with this error

```
 [!] Error: '../singletons/rich-text-editor-selection.js' is imported as an external by lib/toolbars/rich-text-editor-toolbar.js, but is already an existing non-external module id.
Error: '../singletons/rich-text-editor-selection.js' is imported as an external by lib/toolbars/rich-text-editor-toolbar.js, but is already an existing non-external module id.
    at error (/home/runner/work/lrnwebcomponents/lrnwebcomponents/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.fetchResolvedDependency (/home/runner/work/lrnwebcomponents/lrnwebcomponents/node_modules/rollup/dist/shared/node-entry.js:12399:24)
    at ModuleLoader.<anonymous> (/home/runner/work/lrnwebcomponents/lrnwebcomponents/node_modules/rollup/dist/shared/node-entry.js:12296:29)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/lrnwebcomponents/lrnwebcomponents/node_modules/rollup/dist/shared/node-entry.js:38:28)
```

I interpret it as a self reference causing rollup to buckle.

I'd try replacing `../singletons/rich-text-editor-selection.js` with `lib/toolbars/rich-text-editor-toolbar.js` and see if that resolves the issue in rollup.

**Comment by ChristianMurphy** [comment]
Update, I tried

> replacing `../singletons/rich-text-editor-selection.js` with `lib/singletons/rich-text-editor-selection.js` and see if that resolves the issue in rollup.

locally and it appeared to resolve the issue.

I'm less sure that it's a cyclical issue now, I think it may be related to https://github.com/rollup/plugins/issues/481

**Comment by btopro** [comment]
@ChristianMurphy weird cause that's not the direct path and I always though `../` and `./` were prefered for non-rewritten paths

**Comment by btopro** [comment]
moved them all to `import "@lrnwebcomponents/rich-text-editor/lib/singletons/rich-text-editor-selection.js";` and seemed to fix it. thx @ChristianMurphy

**Pull request merged**
