### PR TITLE
Multiple Image Feature

### PR DESCRIPTION
**Pull request by aam198**
Added multiple image component to a11y-compare-image

### CODE REVIEW

**Comment by btopro** [comment]
Thank you for the contribution @aam198 ! Allie or @nikkimk does this change the API for image-compare-slider in anyway? I know that uses it and that we use that tag in production content so want to confirm that the demo in this fork still works for image-compare-slider before accepting. Otherwise looks good.

**Comment by nikkimk** [comment]
> Thank you for the contribution @aam198 ! Allie or @nikkimk does this change the API for image-compare-slider in anyway? I know that uses it and that we use that tag in production content so want to confirm that the demo in this fork still works for image-compare-slider before accepting. Otherwise looks good.
We tested it with Image Compare Slider and it works. No props or methods were removed, only new ones added.

**Comment by btopro** [comment]
Sounds good. Was just checking since some older props were removed. Congrats @aam198 on the first of what we hope are many contributions to our webcomponents 😁

**Comment by nikkimk** [comment]
Yeah those old ones were never really used in a11y-compare-image.

**Pull request merged**
