### PR TITLE
ci(github-actions): add github actions continuous integration

### PR DESCRIPTION
**Pull request by ChristianMurphy**

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
currently failing with:

```
[!] Error: Could not resolve './loading-indicator.js' from iframe-loader.umd.js
Error: Could not resolve './loading-indicator.js' from iframe-loader.umd.js
    at error (/home/runner/work/lrnwebcomponents/lrnwebcomponents/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/home/runner/work/lrnwebcomponents/lrnwebcomponents/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (/home/runner/work/lrnwebcomponents/lrnwebcomponents/node_modules/rollup/dist/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/lrnwebcomponents/lrnwebcomponents/node_modules/rollup/dist/shared/node-entry.js:38:28)

error Command failed with exit code 1.
```
I'm seeing the same error when running `lerna run build` locally.

**Comment by btopro** [comment]
Awesome! Yeah there must be an older package format for that one cause we don't reference umd just include them for other devs

**Comment by ChristianMurphy** [comment]
Tracing this back a bit further
https://github.com/elmsln/lrnwebcomponents/blob/9f50754481ec6a50b5c2adcedd8c455f42f5dd22/elements/iframe-loader/iframe-loader.js#L3
is searching this folder for `loading-indicator` https://github.com/elmsln/lrnwebcomponents/tree/9f50754481ec6a50b5c2adcedd8c455f42f5dd22/elements/iframe-loader

walking back to the original commit https://github.com/elmsln/lrnwebcomponents/commit/5789ba58503373c6e3d4bb880fe661a1857e041f#diff-79992a7dec429c674d2116642a5c2374
it appears that file is/was never checked into source control.
@heyMP  is `loading-indicator` a generated file?

it also may not be referenced/used.
the source appears to later references `loading-indictor`, maybe a type or maybe another component? :man_shrugging: 
https://github.com/elmsln/lrnwebcomponents/blob/792bd5532ea2f087015a97a3bb12891c1621f634/elements/iframe-loader/iframe-loader.js#L114

**Comment by btopro** [comment]
in the category of " @ChristianMurphy is reading our brains and then commenting as we're working" news. (Me and @heyMP were just talking about prospects of GH CI for building assets). I just made a commit to fix that element. Merging this now and let's see what happens :)

**Pull request merged**
