### PR TITLE
Activity box updates

### PR DESCRIPTION
**Pull request by JackWillDavis**
Hi @btopro,

Please could I get a bit of feedback on the method used for handling custom SVGs/CSS Variables in this element?

I've set up a preconfigured list of options for the icon in the activity box which correspond to some of the iconset used in the `simple-icon` component. These will act as the "default" icons which will be available in base ELMSLN and we can override the SVGs being used by providing CSS Variables like so:

```
body {
    --activity-box-icon-settings: url(https://media.example.co.uk/sites/media/bc/files/icons/svgs/cog-icon.svg);
    --activity-box-icon-pencil: url(https://media.example.co.uk/sites/media/bc/files/icons/svgs/pencil-icon.svg);
    --activity-box-icon-bulb: url(https://media.example.co.uk/sites/media/bc/files/icons/svgs/lightbulb-icon.svg);
    --activity-box-icon-sop: url(https://media.example.co.uk/sites/media/bc/files/icons/svgs/s1-sop.svg);
}
```

Given some of the icons have titles like "editor:mode-edit", I've added something which switches them from more friendly names (i.e. pencil) to the right icon title like so:

```
updated(changedProperties) {
    if (super.updated) {
      super.updated(changedProperties);
    }
    changedProperties.forEach((oldValue, propName) => {
      if (propName == "icon") {
        var customIcon = getComputedStyle(this)
          .getPropertyValue("--activity-box-icon-" + `${this[propName]}`)
          .slice(5, -1)
          .replace(/\\/g, "");
        if (customIcon) {
          this.updateIconSource(this, "", customIcon);
        } else {
          /* For certain icons, we need to switch from the friendly name to the actual name of the default icon */
          var icon = `${this[propName]}`;
          switch (this[propName]) {
            case "pencil":
              icon = "editor:mode-edit";
              break;
            case "sop":
              icon = "editor:format-list-bulleted";
              break;
            case "bulb":
              icon = "lightbulb-outline";
              break;
          }
          this.updateIconSource(this, icon, "");
        }
      }
    });
  }
```

I've also added `_simpleIcon` and `_simpleIconSource` to allow the system to switch between using a default icon and providing a `src` for the simple-icon component to display that instead.

Just wanted to see if this was the best approach to take for this particular setup.

We're also having issues editing the slotted content via HAX on the edit page (by clicking and typing in the WYSIWYG). Please could you let me know if this is related to how the component is set up?

### CODE REVIEW

**Comment by btopro** [comment]
The icon thing, is there a reason to load it remotely in this way vs adding the definition / icon directly to the mono repo?

https://github.com/elmsln/lrnwebcomponents/blob/master/elements/simple-icon/lib/simple-icons.js defines the way to define things like the `editor:` and other types of icons. Here are the icons as .svg thing --  https://github.com/elmsln/lrnwebcomponents/tree/master/elements/simple-icon/lib/svgs/editor

So the way it works now is load the `.svg` based on `pathToThing/svgs/editor/icon-name.svg` for `editor:icon-name` type of name. hax-iconset also pulls things in in this way so we could add more icons if we wanted as far as their definition.

Now, the way you're doing it currently is interesting and we have done stuff like this before (the bridge between material => simple-colors css variable names / values makes me think of this). but obviously not preferred in favor oft he icon loader.

Slotted content of a thing being edited can have an issues, it's probably a hax thing related to what we call "grid plates" and I know that @nikkimk has been asking for the "grid plate" connotation to be activated more easily (edit a thing in another thing). It's a pattern we need to clean up more as far as element activation.

**Comment by JackWillDavis** [comment]
I think at the moment, the reason we can't add the icons to the monorepo is a branding issue. We're talking about it internally but we can't open-source all of our icons as a lot of them are part of b-Hive's branding if that makes sense.

It would be the best method to just add them all to the monorepo but I think we're going to have situations when we have to load SVGs remotely for at least some of our icons.

**Comment by btopro** [comment]
yeah, but I think if you look at how that works you could also still remote load or load based on some relative folder path that happens to live on your server but not including a real path. Another option is that putting in a `window.WhatEverYouWantToUseAsThePath` style variable and then elmsln would inject that JS path at run time so that it could load them.

**Comment by JackWillDavis** [comment]
Ah right, so are you saying it would be better if we register another iconset which points to our own set of icons within our own server? 

So, for example, if we wanted to load in an SVG hosted on Media on one of our courses, we would register an iconset (as it does in https://github.com/elmsln/lrnwebcomponents/blob/master/elements/simple-icon/lib/simple-icons.js) which would point to a folder (for example say: `/var/www/elmsln/config/stacks/media/sites/media/bc/files/icons/svgs`) where our own custom icons would be held?

So, if we registered an iconset called `bhive` we could then use `bhive:pencil` for the simple-icon component to grab the file at `/var/www/elmsln/config/stacks/media/sites/media/bc/files/icons/svgs/pencil.svg`?

I'm assuming we would probably need to load in a custom component of our own in order to make that iconset registration - rather than adding it into the monorepo where everyone would be able to see the bhive name but none of the icons?

**Comment by btopro** [comment]
yeah or maybe if we had a generic like "elmsln custom icons" sorta icon library we built registration for but yet it just tapped files that were in like a shared/modules///.... whatever location. Sorta like how we symlink custom modules into the full project so that both are possible

**Comment by JackWillDavis** [comment]
Ah OK, the elmsln symlinked folder sounds good as I think that would be handy for everyone using ELMSLN not just us.

So, if we did that, we'd probably need to change up the activity box settings to allow users to pick an iconset and then an icon wouldn't we?

image

At the moment, it's preconfigured but would it have to change so that the iconset is a dropdown with options like:

* av
* communication
* elmsln-custom
* editor

And then another dropdown which displayed icons for that iconset (for example, if you chose elmsln-custom) it would populate with:

* bulb
* pencil
* cog
* pill

Or is that overcomplicating it?

**Comment by btopro** [comment]
hmm.... I guess it depends on your audience. @nikkimk has a tooling based thing I believe she has in the pipeline so that icons can be visually selected based on which libraries you want to allow. I've been limiting the options available to a handful at times (like stop-note) or at other times just making it a text entry and if you know how to write `editor:edit-mode` or whatever the name is then cool it'll work. Audience for entering this and train-ability are key.

**Comment by JackWillDavis** [comment]
Hi Bryan,

I've gone through and made some changes based on what you mentioned, just wanted to run it by you.

I've changed the icon from a dropdown select and replaced it with a textfield where you can write out the icon identifier (like `editor:mode-edit` manually). I think this will be fine for us in the short term until you roll out the icon selector tooling you mentioned.

I've also registered an `elmsln-custom` iconset and put a symlink to `/var/www/elmsln/config/icons/svgs/` so it connects with our repo. I'm able to load up our own custom icons by typing in `elmsln-custom:bulb` for example.

We're able to target it using CSS Variables with something like:

```
activity-box[icon="elmsln-custom:bulb"] {
 --activity-box-icon-left: -35px;
}
```

I've also added a Boolean option into the HAX configuration which prevents simple-icon from applying colour if required by the user.

Also added in a setting which sorts out padding if there is no icon needed for the component.

**Comment by btopro** [comment]
there's also `simple-icon-lite` which doesn't have color connotations in the same regard which is is simple-icon minus simple-colors. Reasoning of the way you went about that makes sense, I don't know if it'll actually respect the symlink bc of how the build tooling works. My guess is that'll get gobbled up and we'll want some kind of `elmsln-icons` library that actually looks in that semi-hard-coded location but as long as it's working local workflow wise that's fine for the time being.

Timetable no, I just push up whenever. There's so much routinization involved in a build now of the visual assets that I really do check elmsln weeks after verifying whatever works and I'd say I end up doing like a day worth of clean up every couple months in small ways to ensure they play nice with elms but that's only when doing refactors. Adding icons and what not is trivial and I don't have an issue pushing out updated release / versions of elmsln to include things like these assets your working on. We might need to push out a build and go "uhhh... why didnt that work" specifically w/ this icon stuff since that's not really how things tend to work.

Guessing here, but I bet we'll have to do something like....
- iconset definition that points to a hardcoded path like `/assets/icons/svgs/` or something of that nature
- may even need to inject a URL path to get to it

**Pull request merged**
