### PR TITLE
Add elements README and added wcf command help

### PR DESCRIPTION
**Pull request by JAlbert2**

### CODE REVIEW

**Comment by btopro** [comment]
err... what does this do? On rebuild it appends to the main readme or something? Do you have an example of what the output would be of this?

**Comment by JAlbert2** [comment]
It's supposed to create a readme file within the elements folder with the first four lines from each of the elements readme files. I'll take a look at it again

**Comment by btopro** [comment]
oooooo ok, super interesting. I really like that idea! Can you add a reference to it from the main one too so that it's obvious that they can find the elements? Definitely an improvement for docs section, very nice!

**Comment by JAlbert2** [comment]
Did it appear to work? I didn't know if it was actually able to process and change the file

**Comment by btopro** [comment]
I saw an example of it in the PR at one point, it seems like that would work but obviously I'll have to accept, then let it run its build to ensure it does.

I added a follow up for when this has time to go through. https://github.com/elmsln/issues/issues/643

**Pull request merged**
