### PR TITLE
build: ensure path passed to dynamic import is static

### PR DESCRIPTION
**Pull request by ChristianMurphy**
this ensures the plugin will not attempt to transform dynamic imports with dynamic paths

for example
```
import(`${dynamicOne}${dynamicTwo}`)
```
cannot be translated into a static import

https://astexplorer.net/#/gist/16c8cd275ea5b0df3da862d2fb5add9a/7a475625f04e76248fa360e9b263a0df333c8091

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Some parts of this codebase like
https://github.com/elmsln/lrnwebcomponents/blob/eab7cf3ddb5d652108bee8d1a5c97c4b4a356064/elements/dynamic-import-registry/dynamic-import-registry.js#L86
may not be buildable to UMD with rollup

**Comment by btopro** [comment]
Yeah I dono how you use that last one though in a UMD routine. dynamic import registry + wc-autoloader are how we lazy load elements 1 at a time and have them kept track of in the dom. If they can be done that way cool but I dono that it would ever come up given that UMD builds are going to be bundled together in some way most likely while that "element" by design is a singleton to bridge dynamic importing (tho it compiles to AMD / ES5 correctly w/ polyfills)

**Comment by ChristianMurphy** [comment]
addressed https://github.com/elmsln/lrnwebcomponents/pull/451#issuecomment-691538813 in 90807d8

**Comment by ChristianMurphy** [comment]
> dono how you use that last one though in a UMD routine. dynamic import registry + wc-autoloader are how we lazy load elements 1 at a time and have them kept track of in the dom. If they can be done that way cool

It may be possible to get UMD loading dynamically using globals :thinking: 

> If they can be done that way cool but I dono that it would ever come up given that UMD builds are going to be bundled together in some way most likely while that "element" by design is a singleton to bridge dynamic importing (tho it compiles to AMD / ES5 correctly w/ polyfills)

I agree, doing dynamic loading with the UMD build is uncommon enough and could add enough complexity, that it may be worth tabling/backlogging it until there is a request to support it.

**Pull request merged**
